### ISSUE TITLE
vuescroll在我下面这个情况怎么不能滚动呢

### ISSUE THREAD

**Issue by DJun5** [YvesCoding/vuescroll-issue-list-demo#1]
<vue-scroll :ops="ops">
        <ul class="card__list">
          <li class="card__item card__item--blue" v-for="room in roomData ">
            <div class="card__info">
              <div class="info-player">
                <div class="info-player__name">
                  <span class="roomName" v-cloak>{{room.roomName}}&nbsp;</span><span class="onlineNum">{{room.onlineEquipment}}/{{room.totalEquipment}} 在线</span>
                </div>
                <div class="info-image">
                  <img :src="room.imgName" :alt="room.roomID">
                </div>
              </div>
            </div>
          </li>
        </ul>
      </vue-scroll>

**Comment by wangyi7099** [comment]
提供的信息太少了，无法判断
